package com.iplank.fakestats;

import net.runelite.api.Skill;

public class FakeTotalSpoofGenerator {
    static int i = 0;
    public static void main(String[] args)
    {
        String s = "\t\t\t// begin autogenerated\n";
        s += generateChunk(Skill.ATTACK);
        s += generateChunk(Skill.STRENGTH);
        s += generateChunk(Skill.DEFENCE);
        s += generateChunk(Skill.RANGED);
        s += generateChunk(Skill.PRAYER);
        s += generateChunk(Skill.MAGIC);
        s += generateChunk(Skill.RUNECRAFT);
        s += generateChunk(Skill.CONSTRUCTION);
        s += generateChunk(Skill.HITPOINTS);
        s += generateChunk(Skill.AGILITY);
        s += generateChunk(Skill.HERBLORE);
        s += generateChunk(Skill.THIEVING);
        s += generateChunk(Skill.FLETCHING);
        s += generateChunk(Skill.CRAFTING);
        s += generateChunk(Skill.SLAYER);
        s += generateChunk(Skill.HUNTER);
        s += generateChunk(Skill.MINING);
        s += generateChunk(Skill.SMITHING);
        s += generateChunk(Skill.FISHING);
        s += generateChunk(Skill.COOKING);
        s += generateChunk(Skill.FIREMAKING);
        s += generateChunk(Skill.WOODCUTTING);
        s += generateChunk(Skill.FARMING);
        s += "\t\t\t// end autogenerated\n";
        System.out.println(s);
    }

    private static String generateChunk(Skill skill) {
        String skillUppercase = skill.getName().toUpperCase();
        String skillLowercase = skill.getName().toLowerCase();
        String skillName = skill.getName();

        i++;
        String totalChunk =
                /*
                if (config.spoofAttack()) {
                    if (config.attackLevel() <= 99) {
                        total += config.attackLevel();
                    } else if (config.attackLevel() > 99 && config.attackLevel() <= 126 && config.virtualTotal()) {
                        total += config.attackLevel();
                    } else if (config.attackLevel() > 126 && config.virtualTotal()) {
                        total += 126;
                    } else if (config.attackLevel() > 99) {
                        total += 99;
                    }
                } else {
                    total += client.getRealSkillLevel(Skill.ATTACK);
                }
                */
                "\t\t\tif (config.spoof" + skillName + "()) {" + "\n" +
                "\t\t\t\tif (config." + skillLowercase + "Level() <= 99) {" + "\n" +
                "\t\t\t\t\ttotal += config." + skillLowercase +  "Level();" + "\n" +
                "\t\t\t\t} else if (config."+ skillLowercase + "Level() > 99 && config." + skillLowercase + "Level() <= 126 && config.virtualTotal()) {" + "\n" +
                "\t\t\t\t\ttotal += config." + skillLowercase +  "Level();" + "\n" +
                "\t\t\t\t} else if (config."+ skillLowercase + "Level() > 126 && config.virtualTotal()) {" + "\n" +
                "\t\t\t\t\ttotal += 126;" + "\n" +
                "\t\t\t\t} else if (config." + skillLowercase + "Level() > 99) {" + "\n" +
                "\t\t\t\t\ttotal += 99;" + "\n" +
                "\t\t\t\t}" + "\n" +
                "\t\t\t} else {" + "\n" +
                "\t\t\t\ttotal += client.getRealSkillLevel(Skill." + skillUppercase + ");" + "\n" +
                "\t\t\t}" + "\n";
        return totalChunk;
    }
}
