package com.iplank.fakestats;

import net.runelite.api.Skill;

public class PluginGenerator {
    static int i = 0;
    public static void main(String[] args)
    {
        String s = "\t\t// begin autogenerated\n";
        s += generatePlugin(Skill.ATTACK, 1);
        s += generatePlugin(Skill.STRENGTH, 2);
        s += generatePlugin(Skill.DEFENCE, 3);
        s += generatePlugin(Skill.RANGED, 4);
        s += generatePlugin(Skill.PRAYER, 5);
        s += generatePlugin(Skill.MAGIC, 6);
        s += generatePlugin(Skill.RUNECRAFT, 7);
        s += generatePlugin(Skill.CONSTRUCTION, 8);
        s += generatePlugin(Skill.HITPOINTS, 9);
        s += generatePlugin(Skill.AGILITY, 10);
        s += generatePlugin(Skill.HERBLORE, 11);
        s += generatePlugin(Skill.THIEVING, 12);
        s += generatePlugin(Skill.CRAFTING, 13);
        s += generatePlugin(Skill.FLETCHING, 14);
        s += generatePlugin(Skill.SLAYER, 15);
        s += generatePlugin(Skill.HUNTER, 16);
        s += generatePlugin(Skill.MINING, 17);
        s += generatePlugin(Skill.SMITHING, 18);
        s += generatePlugin(Skill.FISHING, 19);
        s += generatePlugin(Skill.COOKING, 20);
        s += generatePlugin(Skill.FIREMAKING, 21);
        s += generatePlugin(Skill.WOODCUTTING, 22);
        s += generatePlugin(Skill.FARMING, 23);
        s += "\t\t// end autogenerated\n";
        System.out.println(s);
    }

    private static String generatePlugin(Skill skill, int childId) {
        String skillLowercase = skill.getName().toLowerCase();
        String skillName = skill.getName();

        i++;
        String pluginChunk =
                "\t\t// " + skillName + " Logic" + "\n" +
                "\t\tif (cachedConfig.spoof" + skillName +  ") {" + "\n" +
                "\t\t\tWidget skillWidget = client.getWidget(WidgetID.SKILLS_GROUP_ID, " + i + ");" + "\n" +
                "\t\t\tif (skillWidget == null) { return; }" + "\n" +
                "\t\t\tWidget[] skillWidgetComponents = skillWidget.getDynamicChildren();" + "\n" +
                "\t\t\tif (skillWidgetComponents.length >= 4) {" + "\n" +
                "\t\t\t\tif (cachedConfig." + skillLowercase + "Level > 99) {" + "\n" +
                "\t\t\t\t\tif (cachedConfig.virtualLevels) {" + "\n" +
                "\t\t\t\t\t\tskillWidgetComponents[3].setText(\"\" + 99);" + "\n" +
                "\t\t\t\t\t\tskillWidgetComponents[4].setText(\"\" + cachedConfig." + skillLowercase + "Level);" + "\n" +
                "\t\t\t\t\t} else {" + "\n" +
                "\t\t\t\t\t\tskillWidgetComponents[3].setText(\"\" + 99);" + "\n" +
                "\t\t\t\t\t\tskillWidgetComponents[4].setText(\"\" + 99);" + "\n" +
                "\t\t\t\t\t}" + "\n" +
                "\t\t\t\t} else {" + "\n" +
                "\t\t\t\t\tskillWidgetComponents[3].setText(\"\" + cachedConfig." + skillLowercase + "Level);" + "\n" +
                "\t\t\t\t\tskillWidgetComponents[4].setText(\"\" + cachedConfig." + skillLowercase + "Level);" + "\n" +
                "\t\t\t\t}" + "\n" +
                "\t\t\t}" + "\n" +
                "\t\t}" + "\n\n";
        return pluginChunk;
    }
}
