package com.iplank.fakestats;

import net.runelite.client.config.Config;
import net.runelite.client.config.ConfigGroup;
import net.runelite.client.config.ConfigSection;
import net.runelite.client.config.ConfigItem;
import net.runelite.client.config.Range;

@ConfigGroup("fakestats")
public interface FakeStatsConfig extends Config
{
	@ConfigItem(
			keyName = "fakeSpoofTotal",
			name = "Spoof Fake Total Level",
			description = "Set Total to Include Spoofed Levels",
			position = -5
	)
	default boolean fakeSpoofTotal() { return true; }

	@ConfigItem(
			keyName = "virtualLevels",
			name = "Enable Virtual Levels",
			description = "Enable Levels 100-126",
			position = -4
	)
	default boolean virtualLevels() { return false; }

	@ConfigItem(
			keyName = "virtualTotal",
			name = "Spoof Fake Virtual Total Level",
			description = "Whether or not to Spoof the Virtual Total Level<br>" +
					"NOTE: Must Enable 'Spoof Fake Total'!",
			position = -3
	)
	default boolean virtualTotal() { return false; }

	enum ModePresets {
		NONE,
		All_200M,
		Maxed,
		Level_Three
	}

	@ConfigItem(
			keyName = "preset",
			name = "Preset Mode",
			description = "Toggle Various Presets for Skills and Total!<br>" +
					"WARNING: Overrides Other Settings!",
			position = -2
	)
	default ModePresets preset() { return ModePresets.NONE; }

	@ConfigSection(
			name = "Total Level",
			description = "Configure the Total Level",
			closedByDefault = true,
			position = -1
	)
	String totalLevelSection = "totalLevelSection";

	@ConfigItem(
			keyName = "spooftotal",
			name = "Spoof Total Level",
			description = "Whether or not to Spoof the Total Level",
			section = totalLevelSection,
			position = 0
	)
	default boolean spoofTotal() { return false; }

	@ConfigItem(
			keyName = "totalLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof the Total Level to<br>" +
					"WARNING: Doesn't Account for Stat Values",
			section = totalLevelSection,
			position = 1
	)
	default int totalLevel() { return 9001; }

	@ConfigItem(
			keyName = "overrideTotalText",
			name = "Override Total Level Text",
			description = "Whether or not to Spoof the Total Level Text",
			section = totalLevelSection,
			position = 2
	)
	default boolean overrideTotalText() { return false; }

	@ConfigItem(
			keyName = "totalLevelText",
			name = "Text to Spoof",
			description = "What Level to Spoof the Total Level Text to<br>" +
					"Use \"br\" inside \"<>\" to signify a new line!",
			section = totalLevelSection,
			position = 3
	)
	default String totalLevelText() { return "Total level:<br>Hello World"; }

	// begin autogenerated
	// begin autogenerated
	@ConfigSection(
			name = "Attack",
			description = "Configure the Attack skill",
			closedByDefault = true,
			position = 0
	)
	String attack = "attack";

	@ConfigItem(
			keyName = "spoofAttack",
			name = "Spoof Attack",
			description = "Whether or not to Spoof Attack",
			section = attack,
			position = 1
	)
	default boolean spoofAttack() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "attackLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Attack to",
			section = attack,
			position = 2
	)
	default int attackLevel() { return 99; }

	@ConfigItem(
			keyName = "attackLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = attack,
			position = 3
	)
	default boolean attackLeft() { return true; }

	@ConfigItem(
			keyName = "attackRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = attack,
			position = 4
	)
	default boolean attackRight() { return true; }

	@ConfigSection(
			name = "Strength",
			description = "Configure the Strength skill",
			closedByDefault = true,
			position = 5
	)
	String strength = "strength";

	@ConfigItem(
			keyName = "spoofStrength",
			name = "Spoof Strength",
			description = "Whether or not to Spoof Strength",
			section = strength,
			position = 6
	)
	default boolean spoofStrength() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "strengthLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Strength to",
			section = strength,
			position = 7
	)
	default int strengthLevel() { return 99; }

	@ConfigItem(
			keyName = "strengthLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = strength,
			position = 8
	)
	default boolean strengthLeft() { return true; }

	@ConfigItem(
			keyName = "strengthRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = strength,
			position = 9
	)
	default boolean strengthRight() { return true; }

	@ConfigSection(
			name = "Defence",
			description = "Configure the Defence skill",
			closedByDefault = true,
			position = 10
	)
	String defence = "defence";

	@ConfigItem(
			keyName = "spoofDefence",
			name = "Spoof Defence",
			description = "Whether or not to Spoof Defence",
			section = defence,
			position = 11
	)
	default boolean spoofDefence() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "defenceLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Defence to",
			section = defence,
			position = 12
	)
	default int defenceLevel() { return 99; }

	@ConfigItem(
			keyName = "defenceLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = defence,
			position = 13
	)
	default boolean defenceLeft() { return true; }

	@ConfigItem(
			keyName = "defenceRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = defence,
			position = 14
	)
	default boolean defenceRight() { return true; }

	@ConfigSection(
			name = "Ranged",
			description = "Configure the Ranged skill",
			closedByDefault = true,
			position = 15
	)
	String ranged = "ranged";

	@ConfigItem(
			keyName = "spoofRanged",
			name = "Spoof Ranged",
			description = "Whether or not to Spoof Ranged",
			section = ranged,
			position = 16
	)
	default boolean spoofRanged() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "rangedLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Ranged to",
			section = ranged,
			position = 17
	)
	default int rangedLevel() { return 99; }

	@ConfigItem(
			keyName = "rangedLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = ranged,
			position = 18
	)
	default boolean rangedLeft() { return true; }

	@ConfigItem(
			keyName = "rangedRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = ranged,
			position = 19
	)
	default boolean rangedRight() { return true; }

	@ConfigSection(
			name = "Prayer",
			description = "Configure the Prayer skill",
			closedByDefault = true,
			position = 20
	)
	String prayer = "prayer";

	@ConfigItem(
			keyName = "spoofPrayer",
			name = "Spoof Prayer",
			description = "Whether or not to Spoof Prayer",
			section = prayer,
			position = 21
	)
	default boolean spoofPrayer() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "prayerLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Prayer to",
			section = prayer,
			position = 22
	)
	default int prayerLevel() { return 99; }

	@ConfigItem(
			keyName = "prayerLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = prayer,
			position = 23
	)
	default boolean prayerLeft() { return true; }

	@ConfigItem(
			keyName = "prayerRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = prayer,
			position = 24
	)
	default boolean prayerRight() { return true; }

	@ConfigSection(
			name = "Magic",
			description = "Configure the Magic skill",
			closedByDefault = true,
			position = 25
	)
	String magic = "magic";

	@ConfigItem(
			keyName = "spoofMagic",
			name = "Spoof Magic",
			description = "Whether or not to Spoof Magic",
			section = magic,
			position = 26
	)
	default boolean spoofMagic() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "magicLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Magic to",
			section = magic,
			position = 27
	)
	default int magicLevel() { return 99; }

	@ConfigItem(
			keyName = "magicLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = magic,
			position = 28
	)
	default boolean magicLeft() { return true; }

	@ConfigItem(
			keyName = "magicRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = magic,
			position = 29
	)
	default boolean magicRight() { return true; }

	@ConfigSection(
			name = "Runecraft",
			description = "Configure the Runecraft skill",
			closedByDefault = true,
			position = 30
	)
	String runecraft = "runecraft";

	@ConfigItem(
			keyName = "spoofRunecraft",
			name = "Spoof Runecraft",
			description = "Whether or not to Spoof Runecraft",
			section = runecraft,
			position = 31
	)
	default boolean spoofRunecraft() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "runecraftLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Runecraft to",
			section = runecraft,
			position = 32
	)
	default int runecraftLevel() { return 99; }

	@ConfigItem(
			keyName = "runecraftLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = runecraft,
			position = 33
	)
	default boolean runecraftLeft() { return true; }

	@ConfigItem(
			keyName = "runecraftRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = runecraft,
			position = 34
	)
	default boolean runecraftRight() { return true; }

	@ConfigSection(
			name = "Construction",
			description = "Configure the Construction skill",
			closedByDefault = true,
			position = 35
	)
	String construction = "construction";

	@ConfigItem(
			keyName = "spoofConstruction",
			name = "Spoof Construction",
			description = "Whether or not to Spoof Construction",
			section = construction,
			position = 36
	)
	default boolean spoofConstruction() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "constructionLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Construction to",
			section = construction,
			position = 37
	)
	default int constructionLevel() { return 99; }

	@ConfigItem(
			keyName = "constructionLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = construction,
			position = 38
	)
	default boolean constructionLeft() { return true; }

	@ConfigItem(
			keyName = "constructionRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = construction,
			position = 39
	)
	default boolean constructionRight() { return true; }

	@ConfigSection(
			name = "Hitpoints",
			description = "Configure the Hitpoints skill",
			closedByDefault = true,
			position = 40
	)
	String hitpoints = "hitpoints";

	@ConfigItem(
			keyName = "spoofHitpoints",
			name = "Spoof Hitpoints",
			description = "Whether or not to Spoof Hitpoints",
			section = hitpoints,
			position = 41
	)
	default boolean spoofHitpoints() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "hitpointsLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Hitpoints to",
			section = hitpoints,
			position = 42
	)
	default int hitpointsLevel() { return 99; }

	@ConfigItem(
			keyName = "hitpointsLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = hitpoints,
			position = 43
	)
	default boolean hitpointsLeft() { return true; }

	@ConfigItem(
			keyName = "hitpointsRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = hitpoints,
			position = 44
	)
	default boolean hitpointsRight() { return true; }

	@ConfigSection(
			name = "Agility",
			description = "Configure the Agility skill",
			closedByDefault = true,
			position = 45
	)
	String agility = "agility";

	@ConfigItem(
			keyName = "spoofAgility",
			name = "Spoof Agility",
			description = "Whether or not to Spoof Agility",
			section = agility,
			position = 46
	)
	default boolean spoofAgility() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "agilityLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Agility to",
			section = agility,
			position = 47
	)
	default int agilityLevel() { return 99; }

	@ConfigItem(
			keyName = "agilityLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = agility,
			position = 48
	)
	default boolean agilityLeft() { return true; }

	@ConfigItem(
			keyName = "agilityRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = agility,
			position = 49
	)
	default boolean agilityRight() { return true; }

	@ConfigSection(
			name = "Herblore",
			description = "Configure the Herblore skill",
			closedByDefault = true,
			position = 50
	)
	String herblore = "herblore";

	@ConfigItem(
			keyName = "spoofHerblore",
			name = "Spoof Herblore",
			description = "Whether or not to Spoof Herblore",
			section = herblore,
			position = 51
	)
	default boolean spoofHerblore() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "herbloreLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Herblore to",
			section = herblore,
			position = 52
	)
	default int herbloreLevel() { return 99; }

	@ConfigItem(
			keyName = "herbloreLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = herblore,
			position = 53
	)
	default boolean herbloreLeft() { return true; }

	@ConfigItem(
			keyName = "herbloreRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = herblore,
			position = 54
	)
	default boolean herbloreRight() { return true; }

	@ConfigSection(
			name = "Thieving",
			description = "Configure the Thieving skill",
			closedByDefault = true,
			position = 55
	)
	String thieving = "thieving";

	@ConfigItem(
			keyName = "spoofThieving",
			name = "Spoof Thieving",
			description = "Whether or not to Spoof Thieving",
			section = thieving,
			position = 56
	)
	default boolean spoofThieving() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "thievingLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Thieving to",
			section = thieving,
			position = 57
	)
	default int thievingLevel() { return 99; }

	@ConfigItem(
			keyName = "thievingLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = thieving,
			position = 58
	)
	default boolean thievingLeft() { return true; }

	@ConfigItem(
			keyName = "thievingRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = thieving,
			position = 59
	)
	default boolean thievingRight() { return true; }

	@ConfigSection(
			name = "Crafting",
			description = "Configure the Crafting skill",
			closedByDefault = true,
			position = 60
	)
	String crafting = "crafting";

	@ConfigItem(
			keyName = "spoofCrafting",
			name = "Spoof Crafting",
			description = "Whether or not to Spoof Crafting",
			section = crafting,
			position = 61
	)
	default boolean spoofCrafting() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "craftingLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Crafting to",
			section = crafting,
			position = 62
	)
	default int craftingLevel() { return 99; }

	@ConfigItem(
			keyName = "craftingLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = crafting,
			position = 63
	)
	default boolean craftingLeft() { return true; }

	@ConfigItem(
			keyName = "craftingRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = crafting,
			position = 64
	)
	default boolean craftingRight() { return true; }

	@ConfigSection(
			name = "Fletching",
			description = "Configure the Fletching skill",
			closedByDefault = true,
			position = 65
	)
	String fletching = "fletching";

	@ConfigItem(
			keyName = "spoofFletching",
			name = "Spoof Fletching",
			description = "Whether or not to Spoof Fletching",
			section = fletching,
			position = 66
	)
	default boolean spoofFletching() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "fletchingLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Fletching to",
			section = fletching,
			position = 67
	)
	default int fletchingLevel() { return 99; }

	@ConfigItem(
			keyName = "fletchingLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = fletching,
			position = 68
	)
	default boolean fletchingLeft() { return true; }

	@ConfigItem(
			keyName = "fletchingRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = fletching,
			position = 69
	)
	default boolean fletchingRight() { return true; }

	@ConfigSection(
			name = "Slayer",
			description = "Configure the Slayer skill",
			closedByDefault = true,
			position = 70
	)
	String slayer = "slayer";

	@ConfigItem(
			keyName = "spoofSlayer",
			name = "Spoof Slayer",
			description = "Whether or not to Spoof Slayer",
			section = slayer,
			position = 71
	)
	default boolean spoofSlayer() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "slayerLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Slayer to",
			section = slayer,
			position = 72
	)
	default int slayerLevel() { return 99; }

	@ConfigItem(
			keyName = "slayerLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = slayer,
			position = 73
	)
	default boolean slayerLeft() { return true; }

	@ConfigItem(
			keyName = "slayerRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = slayer,
			position = 74
	)
	default boolean slayerRight() { return true; }

	@ConfigSection(
			name = "Hunter",
			description = "Configure the Hunter skill",
			closedByDefault = true,
			position = 75
	)
	String hunter = "hunter";

	@ConfigItem(
			keyName = "spoofHunter",
			name = "Spoof Hunter",
			description = "Whether or not to Spoof Hunter",
			section = hunter,
			position = 76
	)
	default boolean spoofHunter() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "hunterLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Hunter to",
			section = hunter,
			position = 77
	)
	default int hunterLevel() { return 99; }

	@ConfigItem(
			keyName = "hunterLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = hunter,
			position = 78
	)
	default boolean hunterLeft() { return true; }

	@ConfigItem(
			keyName = "hunterRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = hunter,
			position = 79
	)
	default boolean hunterRight() { return true; }

	@ConfigSection(
			name = "Mining",
			description = "Configure the Mining skill",
			closedByDefault = true,
			position = 80
	)
	String mining = "mining";

	@ConfigItem(
			keyName = "spoofMining",
			name = "Spoof Mining",
			description = "Whether or not to Spoof Mining",
			section = mining,
			position = 81
	)
	default boolean spoofMining() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "miningLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Mining to",
			section = mining,
			position = 82
	)
	default int miningLevel() { return 99; }

	@ConfigItem(
			keyName = "miningLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = mining,
			position = 83
	)
	default boolean miningLeft() { return true; }

	@ConfigItem(
			keyName = "miningRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = mining,
			position = 84
	)
	default boolean miningRight() { return true; }

	@ConfigSection(
			name = "Smithing",
			description = "Configure the Smithing skill",
			closedByDefault = true,
			position = 85
	)
	String smithing = "smithing";

	@ConfigItem(
			keyName = "spoofSmithing",
			name = "Spoof Smithing",
			description = "Whether or not to Spoof Smithing",
			section = smithing,
			position = 86
	)
	default boolean spoofSmithing() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "smithingLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Smithing to",
			section = smithing,
			position = 87
	)
	default int smithingLevel() { return 99; }

	@ConfigItem(
			keyName = "smithingLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = smithing,
			position = 88
	)
	default boolean smithingLeft() { return true; }

	@ConfigItem(
			keyName = "smithingRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = smithing,
			position = 89
	)
	default boolean smithingRight() { return true; }

	@ConfigSection(
			name = "Fishing",
			description = "Configure the Fishing skill",
			closedByDefault = true,
			position = 90
	)
	String fishing = "fishing";

	@ConfigItem(
			keyName = "spoofFishing",
			name = "Spoof Fishing",
			description = "Whether or not to Spoof Fishing",
			section = fishing,
			position = 91
	)
	default boolean spoofFishing() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "fishingLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Fishing to",
			section = fishing,
			position = 92
	)
	default int fishingLevel() { return 99; }

	@ConfigItem(
			keyName = "fishingLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = fishing,
			position = 93
	)
	default boolean fishingLeft() { return true; }

	@ConfigItem(
			keyName = "fishingRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = fishing,
			position = 94
	)
	default boolean fishingRight() { return true; }

	@ConfigSection(
			name = "Cooking",
			description = "Configure the Cooking skill",
			closedByDefault = true,
			position = 95
	)
	String cooking = "cooking";

	@ConfigItem(
			keyName = "spoofCooking",
			name = "Spoof Cooking",
			description = "Whether or not to Spoof Cooking",
			section = cooking,
			position = 96
	)
	default boolean spoofCooking() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "cookingLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Cooking to",
			section = cooking,
			position = 97
	)
	default int cookingLevel() { return 99; }

	@ConfigItem(
			keyName = "cookingLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = cooking,
			position = 98
	)
	default boolean cookingLeft() { return true; }

	@ConfigItem(
			keyName = "cookingRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = cooking,
			position = 99
	)
	default boolean cookingRight() { return true; }

	@ConfigSection(
			name = "Firemaking",
			description = "Configure the Firemaking skill",
			closedByDefault = true,
			position = 100
	)
	String firemaking = "firemaking";

	@ConfigItem(
			keyName = "spoofFiremaking",
			name = "Spoof Firemaking",
			description = "Whether or not to Spoof Firemaking",
			section = firemaking,
			position = 101
	)
	default boolean spoofFiremaking() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "firemakingLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Firemaking to",
			section = firemaking,
			position = 102
	)
	default int firemakingLevel() { return 99; }

	@ConfigItem(
			keyName = "firemakingLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = firemaking,
			position = 103
	)
	default boolean firemakingLeft() { return true; }

	@ConfigItem(
			keyName = "firemakingRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = firemaking,
			position = 104
	)
	default boolean firemakingRight() { return true; }

	@ConfigSection(
			name = "Woodcutting",
			description = "Configure the Woodcutting skill",
			closedByDefault = true,
			position = 105
	)
	String woodcutting = "woodcutting";

	@ConfigItem(
			keyName = "spoofWoodcutting",
			name = "Spoof Woodcutting",
			description = "Whether or not to Spoof Woodcutting",
			section = woodcutting,
			position = 106
	)
	default boolean spoofWoodcutting() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "woodcuttingLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Woodcutting to",
			section = woodcutting,
			position = 107
	)
	default int woodcuttingLevel() { return 99; }

	@ConfigItem(
			keyName = "woodcuttingLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = woodcutting,
			position = 108
	)
	default boolean woodcuttingLeft() { return true; }

	@ConfigItem(
			keyName = "woodcuttingRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = woodcutting,
			position = 109
	)
	default boolean woodcuttingRight() { return true; }

	@ConfigSection(
			name = "Farming",
			description = "Configure the Farming skill",
			closedByDefault = true,
			position = 110
	)
	String farming = "farming";

	@ConfigItem(
			keyName = "spoofFarming",
			name = "Spoof Farming",
			description = "Whether or not to Spoof Farming",
			section = farming,
			position = 111
	)
	default boolean spoofFarming() { return false; }

	@Range(
			min = 1,
			max = 126
	)
	@ConfigItem(
			keyName = "farmingLevel",
			name = "Level to Spoof",
			description = "What Level to Spoof Farming to",
			section = farming,
			position = 112
	)
	default int farmingLevel() { return 99; }

	@ConfigItem(
			keyName = "farmingLeft",
			name = "Spoof Left Value",
			description = "Spoof the left digit of the skill display?",
			section = farming,
			position = 113
	)
	default boolean farmingLeft() { return true; }

	@ConfigItem(
			keyName = "farmingRight",
			name = "Spoof Right Value",
			description = "Spoof the right digit of the skill display?",
			section = farming,
			position = 114
	)
	default boolean farmingRight() { return true; }

	// end autogenerated
}
